all: fixed-to-float float-to-fixed fixed-arithmetic

fixed-to-float: fixed-to-float.c
	gcc -o fixed-to-float -O -g fixed-to-float.c

float-to-fixed: float-to-fixed.c
	gcc -o float-to-fixed -O -g float-to-fixed.c

fixed-arithmetic: fixed-arithmetic.c
	gcc -o fixed-arithmetic -O -g fixed-arithmetic.c
